### PR TITLE
Added HeytingAlgebra, Semiring, Ring

### PR DESCRIPTION
**Pull request by xgrommx**

### CODE REVIEW

**Comment by hdgarrood** [comment]
Currently there's no `Semiring Either` instance, because we haven't found a law-abiding one. See https://github.com/purescript/purescript-either/pull/37 for example. Might the `Semiring` instance here suffer from the same problem for a data type like `Either`?

**Comment by xgrommx** [comment]
@hdgarrood I don't think that it correct (maybe it impossible, but I can be wrong)
Firstly we need type equality for `a` and `b` (in `Either a b`)

**Comment by LiamGoodacre** [comment]
@hdgarrood this change doesn't include implementations for `Sum`.  Only `Constructor`, `Argument`, `NoArguments`, and `Product`.

**Comment by hdgarrood** [comment]
Ah of course, thanks.

**Comment by LiamGoodacre** [comment]
Thanks again!

**Pull request merged**
